# Generated by Django 6.0.3 on 2026-03-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_collection_be', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='date_precision',
            field=models.CharField(choices=[('full', 'Full date'), ('month', 'Month and year'), ('year', 'Year only')], default='full', max_length=5),
        ),
    ]
