# Generated by Django 3.1.1 on 2020-09-08 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_collection_be', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='tracklist',
        ),
    ]
