# Generated by Django 3.1.1 on 2020-09-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_collection_be', '0002_remove_album_tracklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='track',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
