# Generated by Django 3.1.1 on 2020-09-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_collection_be', '0004_auto_20200908_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
