# Generated by Django 3.1.1 on 2020-09-10 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_collection_be', '0005_album_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['track']},
        ),
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('album', 'track')},
        ),
    ]
