# Generated by Django 3.1.1 on 2020-09-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_collection_be', '0006_auto_20200910_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='acquired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='track',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
