# Generated by Django 3.1.1 on 2020-11-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record_collection_be', '0008_auto_20200911_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist_string',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
