# Generated by Django 6.0.3 on 2026-03-12 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record_collection_be', '0010_alter_album_id_alter_artist_id_alter_song_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together=set(),
        ),
    ]
